apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator-sa
  namespace: homework-crd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysql-operator-role
subjects:
  - kind: ServiceAccount
    name: mysql-operator-sa
    namespace: homework-crd
