repositories:
 - name: bitnami
   url: https://charts.bitnami.com/bitnami

releases:
- name: kafka-dev
  namespace: dev
  chart: bitnami/kafka
  set:
  - name: controller.persistence.enabled
    value: false
  - name: broker.persistence.enabled
    value: false
  - name: controller.replicaCount
    value: 1
  # dev
  - name: broker.replicaCount
    value: 1
  - name: image.tag
    value: latest
  - name: listeners.client.protocol
    value: PLAINTEXT
  - name: listeners.interbroker.protocol
    value: PLAINTEXT

- name: kafka-prod
  namespace: prod
  chart: bitnami/kafka
  version: "25.3.5"
  set:
  - name: controller.persistence.enabled
    value: false
  - name: broker.persistence.enabled
    value: false
  - name: controller.replicaCount
    value: 3
  # prod
  - name: image.tag
    value: 3.5.2-debian-12-r26
  - name: listeners.client.protocol
    value: SASL_PLAINTEXT
  - name: listeners.interbroker.protocol
    value: SASL_PLAINTEXT
