apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: custom-ng
        imagePullPolicy: Always
        image: docker.io/sounds1interesting/test-repo:latest
        ports:
        - containerPort: 80
        - containerPort: 9113
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: homework
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http 
      protocol: TCP
      port: 80
      targetPort: 80
    - name: metrics
      port: 9113
      targetPort: 9113
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-servicemonitor
  labels:
    app: nginx
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
  - port: metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - homework
