apiVersion: v1
kind: Service
metadata:
  name: homework-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.label.app }}
  ports:
    - name: {{ .Values.service.name }}
      protocol: TCP
      port: {{ .Values.service.port }}
      # default: targetPort = port if targetPort is not specified
