apiVersion: v1
kind: PersistentVolume
metadata:
  name: homework-pv
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistence.storageClass.name }} # в зависимости от используемого storageclass
  capacity:
    storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistence.accessMode }}
  hostPath:
    path: /mnt/homework-pv-custom
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.volumeClaim.name }}
  namespace: {{ .Values.namespace }}
spec:
  volumeMode: Filesystem # Actually, it's default
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass.name }} # If empty will be used default SC in cluster
