apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.name }}-role
rules:
- apiGroups: [""]
  resources: {{ .Values.rbac.rules.apiGroups.resources }}
  verbs: {{ .Values.rbac.rules.apiGroups.verbs }}
- nonResourceURLs: {{ .Values.rbac.rules.nonResourceURLs.value }}
  verbs: {{ .Values.rbac.rules.apiGroups.verbs }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.serviceAccount.name }}-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAdminAccount.name }}
  namespace: {{ .Values.namespace }}
secrets:
  - name: {{ .Values.serviceAdminAccount.name }}-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceAdminAccount.name }}-secret
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAdminAccount.name }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAdminAccount.name }}-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAdminAccount.name }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
