apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.persistence.storageClass.name }}
  namespace: {{ .Values.namespace }}
provisioner: {{ .Values.persistence.storageClass.provisioner }}
reclaimPolicy: {{ .Values.persistence.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.persistence.storageClass.volumeBindingMode }}
