apiVersion: v1
kind: PersistentVolume
metadata:
  name: homework-pv
  namespace: homework
spec:
  storageClassName: homework-sc
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/homework-pv-custom
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework-pvc
  namespace: homework
spec:
  volumeMode: Filesystem # Actually it's default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: homework-sc # If empty will be used default SC in cluster
